### PR TITLE
Doorkeeper 4.1 and 4.2 support

### PR DESCRIPTION
**Pull request by daveallie**
Added support for doorkeeper 4.1 and 4.2.

Tests seems to be passing, added lines to `.travis.yml`

### CODE REVIEW

**Comment by antek-drzewiecki** [comment]
Thanks @daveallie :+1:

**Comment by steveh** [comment]
@antek-drzewiecki could you release a new version for this please?

**Comment by antek-drzewiecki** [comment]
@steveh , done  released. :)

**Comment by daveallie** [comment]
Looks like you forgot to update the requirements section of the readme @antek-drzewiecki, should be
> Doorkeeper > 1.4.0 and < 4.3

**Comment by antek-drzewiecki** [comment]
You are correct, thanks. It went trough my checks.

**Pull request merged**
