### PR TITLE
Create rails generator for initial config.

### PR DESCRIPTION
**Pull request by whatasunnyday**

### CODE REVIEW

**Comment by antek-drzewiecki** [comment]
Thank you for your contribution :+1: ! Great feature indeed. Do you mind adding a spec for the installer, so we can make sure it will pass against all supported rails versions?

**Comment by whatasunnyday** [comment]
FYI, I'm waiting on this to resolve: https://github.com/stevehodgkiss/generator_spec/issues/39

**Comment by whatasunnyday** [comment]
@antek-drzewiecki Branch is updated with a spec for the installer. Let me know if there's anything else do to improve this PR.

**Comment by antek-drzewiecki** [comment]
Its great like it is! Once I tested and merged the Doorkeeper 2.0 branch ill merge this one. Expect it on Thursday as a maximum.

**Comment by whatasunnyday** [comment]
Thanks again for your wonderful library and making it easy to contribute to.

**Pull request merged**
